version: "3"

services:
  node_basic:
    build: ./server
    ports:
      - 3000:3000
    working_dir: /usr/src/app

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/env/local/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/server.crt:/var/lib/runtime_cert/server.crt
      - ./certs/server.key:/var/lib/runtime_cert/server.key
      - ./certs/ca.crt:/etc/nginx/client_certs/ca.crt


