version: "3"

services:
  node_basic:
    build:
      context: ../../../server
    ports:
      - 3000:3000
    working_dir: /usr/src/app

  nginx:
    image: nginx
    ports:
      - "8090:8090"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../../certs/server.crt:/etc/ssl/server.crt
      - ../../../certs/server.key:/etc/ssl/server.key
      - ../../../certs/ca.crt:/etc/nginx/client_certs/ca.crt


